check version

diff --git a/ubuntu14.04/gpu/cuda8-cudnn5/caffe2-v0.7-notebook/Dockerfile b/ubuntu14.04/gpu/cuda8-cudnn5/caffe2-v0.7-notebook/Dockerfile
--- a/ubuntu14.04/gpu/cuda8-cudnn5/caffe2-v0.7-notebook/Dockerfile
+++ b/ubuntu14.04/gpu/cuda8-cudnn5/caffe2-v0.7-notebook/Dockerfile
@@ -93,12 +93,12 @@ RUN pip2 install \
 
 # Clone and build
 RUN git clone --recursive https://github.com/caffe2/caffe2.git && cd caffe2
-RUN git checkout remotes/origin/r${CAFFE2_VERSION}
-RUN make && cd build && sudo make install
-RUN python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
+# RUN git checkout remotes/origin/r${CAFFE2_VERSION}
+# RUN make && cd build && sudo make install
+# RUN python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
 
 # Test your gpu
-RUN python -m caffe2.python.operator_test.relu_op_test
+# RUN python -m caffe2.python.operator_test.relu_op_test
 
 # Make sure these ENV variables are set
 # echo $PYTHONPATH
